services:
  chatbot:
    container_name: "chatbot-rag-backend"
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot/data:/app/data
      - ./chatbot/chroma_db:/app/chroma_db
    env_file:
      - ./chatbot/.env
    restart: unless-stopped