services:
  chatbot:
    container_name: "chatbot-rag-backend"
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot/data:/app/data
      - ./chatbot/chroma_db:/app/chroma_db
    env_file:
      - ./chatbot/.env
    restart: unless-stopped

  web:
    container_name: "nathanieljr-web"
    build:
      context: ./web/nathanieljr-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://chatbot:8000/chatbot
    depends_on:
      - chatbot
    restart: unless-stopped