name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/nathanieljr-portfolio-web-aws 

            git pull origin main

            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > ./chatbot/.env
            echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> ./chatbot/.env

            echo "NEXT_PUBLIC_API_URL=http://${{ secrets.HOST }}:8000/chatbot" > ./web/nathanieljr-web/.env

            docker-compose up -d --build

            docker system prune -af

            docker ps
